language: ruby
rvm:
  - "2.0.0"

before_script:
  - psql -c "CREATE USER rooms WITH PASSWORD 'rooms';" -U postgres
  - psql -c 'create database rooms_test;' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE rooms_test to rooms'; -U postgres
  - rake db:migrate

addons:
  postgresql: "9.3"


cache: bundler

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
