language: ruby
rvm:
  - "2.0.0"

before_script:
  - psql -c 'create database rooms_test;' -U postgres

addons:
  postgresql: "9.3"

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
