language: ruby
bundler_args: --without debug
rvm:
  - "2.1.0"
  - "2.0.0"

before_script:
  - psql -c 'create database myapp_test;' -U postgres

  #- psql -c "CREATE USER rooms WITH PASSWORD 'rooms';" -U postgres
  #- psql -c "CREATE DATABASE rooms_test;" -U postgres
  #- psql -c "GRANT ALL PRIVILEGES ON DATABASE rooms_test to rooms;" -U postgres
  - bundle exec rake db:schema:load

addons:
  postgresql: "9.3"


cache: bundler


addons:
    code_climate:
        repo_token: de58995f211cd6a4d351744bed6cbce8985aec0d4ea5621e0795b202cc74a25a

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
