ROOMS_FACEBOOK_APP_ID: "330390967090243"
ROOMS_FACEBOOK_SECRET: "e9219fdebaee11b16d845cc000d78797"

ROOMS_MAIL_PASSWORD_DEV: "SClara_1975"
ROOMS_MAIL_USERNAME_DEV: "mywebroom@mywebroom.com"
ROOMS_MAIL_HOST_DEV: "localhost:3000"

ROOMS_MAIL_PASSWORD_PRO: "SClara_1975"
ROOMS_MAIL_USERNAME_PRO: "mywebroom@mywebroom.com"
ROOMS_MAIL_HOST_PRO: "sleepy-scrubland-1880.herokuapp.com"

ROOMS_IMAGE_MAGICK_PATH: "/usr/bin/"
