require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BookmarksCategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # BookmarksCategory. As you add validations to BookmarksCategory, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BookmarksCategoriesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all bookmarks_categories as @bookmarks_categories" do
      bookmarks_category = BookmarksCategory.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bookmarks_categories).should eq([bookmarks_category])
    end
  end

  describe "GET show" do
    it "assigns the requested bookmarks_category as @bookmarks_category" do
      bookmarks_category = BookmarksCategory.create! valid_attributes
      get :show, {:id => bookmarks_category.to_param}, valid_session
      assigns(:bookmarks_category).should eq(bookmarks_category)
    end
  end

  describe "GET new" do
    it "assigns a new bookmarks_category as @bookmarks_category" do
      get :new, {}, valid_session
      assigns(:bookmarks_category).should be_a_new(BookmarksCategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested bookmarks_category as @bookmarks_category" do
      bookmarks_category = BookmarksCategory.create! valid_attributes
      get :edit, {:id => bookmarks_category.to_param}, valid_session
      assigns(:bookmarks_category).should eq(bookmarks_category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BookmarksCategory" do
        expect {
          post :create, {:bookmarks_category => valid_attributes}, valid_session
        }.to change(BookmarksCategory, :count).by(1)
      end

      it "assigns a newly created bookmarks_category as @bookmarks_category" do
        post :create, {:bookmarks_category => valid_attributes}, valid_session
        assigns(:bookmarks_category).should be_a(BookmarksCategory)
        assigns(:bookmarks_category).should be_persisted
      end

      it "redirects to the created bookmarks_category" do
        post :create, {:bookmarks_category => valid_attributes}, valid_session
        response.should redirect_to(BookmarksCategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bookmarks_category as @bookmarks_category" do
        # Trigger the behavior that occurs when invalid params are submitted
        BookmarksCategory.any_instance.stub(:save).and_return(false)
        post :create, {:bookmarks_category => {}}, valid_session
        assigns(:bookmarks_category).should be_a_new(BookmarksCategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BookmarksCategory.any_instance.stub(:save).and_return(false)
        post :create, {:bookmarks_category => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bookmarks_category" do
        bookmarks_category = BookmarksCategory.create! valid_attributes
        # Assuming there are no other bookmarks_categories in the database, this
        # specifies that the BookmarksCategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BookmarksCategory.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => bookmarks_category.to_param, :bookmarks_category => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested bookmarks_category as @bookmarks_category" do
        bookmarks_category = BookmarksCategory.create! valid_attributes
        put :update, {:id => bookmarks_category.to_param, :bookmarks_category => valid_attributes}, valid_session
        assigns(:bookmarks_category).should eq(bookmarks_category)
      end

      it "redirects to the bookmarks_category" do
        bookmarks_category = BookmarksCategory.create! valid_attributes
        put :update, {:id => bookmarks_category.to_param, :bookmarks_category => valid_attributes}, valid_session
        response.should redirect_to(bookmarks_category)
      end
    end

    describe "with invalid params" do
      it "assigns the bookmarks_category as @bookmarks_category" do
        bookmarks_category = BookmarksCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BookmarksCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => bookmarks_category.to_param, :bookmarks_category => {}}, valid_session
        assigns(:bookmarks_category).should eq(bookmarks_category)
      end

      it "re-renders the 'edit' template" do
        bookmarks_category = BookmarksCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BookmarksCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => bookmarks_category.to_param, :bookmarks_category => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bookmarks_category" do
      bookmarks_category = BookmarksCategory.create! valid_attributes
      expect {
        delete :destroy, {:id => bookmarks_category.to_param}, valid_session
      }.to change(BookmarksCategory, :count).by(-1)
    end

    it "redirects to the bookmarks_categories list" do
      bookmarks_category = BookmarksCategory.create! valid_attributes
      delete :destroy, {:id => bookmarks_category.to_param}, valid_session
      response.should redirect_to(bookmarks_categories_url)
    end
  end

end
