require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BundlesBookmarksController do

  # This should return the minimal set of attributes required to create a valid
  # BundlesBookmark. As you add validations to BundlesBookmark, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BundlesBookmarksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all bundles_bookmarks as @bundles_bookmarks" do
      bundles_bookmark = BundlesBookmark.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bundles_bookmarks).should eq([bundles_bookmark])
    end
  end

  describe "GET show" do
    it "assigns the requested bundles_bookmark as @bundles_bookmark" do
      bundles_bookmark = BundlesBookmark.create! valid_attributes
      get :show, {:id => bundles_bookmark.to_param}, valid_session
      assigns(:bundles_bookmark).should eq(bundles_bookmark)
    end
  end

  describe "GET new" do
    it "assigns a new bundles_bookmark as @bundles_bookmark" do
      get :new, {}, valid_session
      assigns(:bundles_bookmark).should be_a_new(BundlesBookmark)
    end
  end

  describe "GET edit" do
    it "assigns the requested bundles_bookmark as @bundles_bookmark" do
      bundles_bookmark = BundlesBookmark.create! valid_attributes
      get :edit, {:id => bundles_bookmark.to_param}, valid_session
      assigns(:bundles_bookmark).should eq(bundles_bookmark)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BundlesBookmark" do
        expect {
          post :create, {:bundles_bookmark => valid_attributes}, valid_session
        }.to change(BundlesBookmark, :count).by(1)
      end

      it "assigns a newly created bundles_bookmark as @bundles_bookmark" do
        post :create, {:bundles_bookmark => valid_attributes}, valid_session
        assigns(:bundles_bookmark).should be_a(BundlesBookmark)
        assigns(:bundles_bookmark).should be_persisted
      end

      it "redirects to the created bundles_bookmark" do
        post :create, {:bundles_bookmark => valid_attributes}, valid_session
        response.should redirect_to(BundlesBookmark.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bundles_bookmark as @bundles_bookmark" do
        # Trigger the behavior that occurs when invalid params are submitted
        BundlesBookmark.any_instance.stub(:save).and_return(false)
        post :create, {:bundles_bookmark => {}}, valid_session
        assigns(:bundles_bookmark).should be_a_new(BundlesBookmark)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BundlesBookmark.any_instance.stub(:save).and_return(false)
        post :create, {:bundles_bookmark => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bundles_bookmark" do
        bundles_bookmark = BundlesBookmark.create! valid_attributes
        # Assuming there are no other bundles_bookmarks in the database, this
        # specifies that the BundlesBookmark created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BundlesBookmark.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => bundles_bookmark.to_param, :bundles_bookmark => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested bundles_bookmark as @bundles_bookmark" do
        bundles_bookmark = BundlesBookmark.create! valid_attributes
        put :update, {:id => bundles_bookmark.to_param, :bundles_bookmark => valid_attributes}, valid_session
        assigns(:bundles_bookmark).should eq(bundles_bookmark)
      end

      it "redirects to the bundles_bookmark" do
        bundles_bookmark = BundlesBookmark.create! valid_attributes
        put :update, {:id => bundles_bookmark.to_param, :bundles_bookmark => valid_attributes}, valid_session
        response.should redirect_to(bundles_bookmark)
      end
    end

    describe "with invalid params" do
      it "assigns the bundles_bookmark as @bundles_bookmark" do
        bundles_bookmark = BundlesBookmark.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BundlesBookmark.any_instance.stub(:save).and_return(false)
        put :update, {:id => bundles_bookmark.to_param, :bundles_bookmark => {}}, valid_session
        assigns(:bundles_bookmark).should eq(bundles_bookmark)
      end

      it "re-renders the 'edit' template" do
        bundles_bookmark = BundlesBookmark.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BundlesBookmark.any_instance.stub(:save).and_return(false)
        put :update, {:id => bundles_bookmark.to_param, :bundles_bookmark => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bundles_bookmark" do
      bundles_bookmark = BundlesBookmark.create! valid_attributes
      expect {
        delete :destroy, {:id => bundles_bookmark.to_param}, valid_session
      }.to change(BundlesBookmark, :count).by(-1)
    end

    it "redirects to the bundles_bookmarks list" do
      bundles_bookmark = BundlesBookmark.create! valid_attributes
      delete :destroy, {:id => bundles_bookmark.to_param}, valid_session
      response.should redirect_to(bundles_bookmarks_url)
    end
  end

end
