require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ItemsDesignsController do

  # This should return the minimal set of attributes required to create a valid
  # ItemsDesign. As you add validations to ItemsDesign, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ItemsDesignsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all items_designs as @items_designs" do
      items_design = ItemsDesign.create! valid_attributes
      get :index, {}, valid_session
      assigns(:items_designs).should eq([items_design])
    end
  end

  describe "GET show" do
    it "assigns the requested items_design as @items_design" do
      items_design = ItemsDesign.create! valid_attributes
      get :show, {:id => items_design.to_param}, valid_session
      assigns(:items_design).should eq(items_design)
    end
  end

  describe "GET new" do
    it "assigns a new items_design as @items_design" do
      get :new, {}, valid_session
      assigns(:items_design).should be_a_new(ItemsDesign)
    end
  end

  describe "GET edit" do
    it "assigns the requested items_design as @items_design" do
      items_design = ItemsDesign.create! valid_attributes
      get :edit, {:id => items_design.to_param}, valid_session
      assigns(:items_design).should eq(items_design)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ItemsDesign" do
        expect {
          post :create, {:items_design => valid_attributes}, valid_session
        }.to change(ItemsDesign, :count).by(1)
      end

      it "assigns a newly created items_design as @items_design" do
        post :create, {:items_design => valid_attributes}, valid_session
        assigns(:items_design).should be_a(ItemsDesign)
        assigns(:items_design).should be_persisted
      end

      it "redirects to the created items_design" do
        post :create, {:items_design => valid_attributes}, valid_session
        response.should redirect_to(ItemsDesign.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved items_design as @items_design" do
        # Trigger the behavior that occurs when invalid params are submitted
        ItemsDesign.any_instance.stub(:save).and_return(false)
        post :create, {:items_design => {}}, valid_session
        assigns(:items_design).should be_a_new(ItemsDesign)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ItemsDesign.any_instance.stub(:save).and_return(false)
        post :create, {:items_design => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested items_design" do
        items_design = ItemsDesign.create! valid_attributes
        # Assuming there are no other items_designs in the database, this
        # specifies that the ItemsDesign created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ItemsDesign.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => items_design.to_param, :items_design => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested items_design as @items_design" do
        items_design = ItemsDesign.create! valid_attributes
        put :update, {:id => items_design.to_param, :items_design => valid_attributes}, valid_session
        assigns(:items_design).should eq(items_design)
      end

      it "redirects to the items_design" do
        items_design = ItemsDesign.create! valid_attributes
        put :update, {:id => items_design.to_param, :items_design => valid_attributes}, valid_session
        response.should redirect_to(items_design)
      end
    end

    describe "with invalid params" do
      it "assigns the items_design as @items_design" do
        items_design = ItemsDesign.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ItemsDesign.any_instance.stub(:save).and_return(false)
        put :update, {:id => items_design.to_param, :items_design => {}}, valid_session
        assigns(:items_design).should eq(items_design)
      end

      it "re-renders the 'edit' template" do
        items_design = ItemsDesign.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ItemsDesign.any_instance.stub(:save).and_return(false)
        put :update, {:id => items_design.to_param, :items_design => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested items_design" do
      items_design = ItemsDesign.create! valid_attributes
      expect {
        delete :destroy, {:id => items_design.to_param}, valid_session
      }.to change(ItemsDesign, :count).by(-1)
    end

    it "redirects to the items_designs list" do
      items_design = ItemsDesign.create! valid_attributes
      delete :destroy, {:id => items_design.to_param}, valid_session
      response.should redirect_to(items_designs_url)
    end
  end

end
