require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StaticContentsController do

  # This should return the minimal set of attributes required to create a valid
  # StaticContent. As you add validations to StaticContent, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StaticContentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all static_contents as @static_contents" do
      static_content = StaticContent.create! valid_attributes
      get :index, {}, valid_session
      assigns(:static_contents).should eq([static_content])
    end
  end

  describe "GET show" do
    it "assigns the requested static_content as @static_content" do
      static_content = StaticContent.create! valid_attributes
      get :show, {:id => static_content.to_param}, valid_session
      assigns(:static_content).should eq(static_content)
    end
  end

  describe "GET new" do
    it "assigns a new static_content as @static_content" do
      get :new, {}, valid_session
      assigns(:static_content).should be_a_new(StaticContent)
    end
  end

  describe "GET edit" do
    it "assigns the requested static_content as @static_content" do
      static_content = StaticContent.create! valid_attributes
      get :edit, {:id => static_content.to_param}, valid_session
      assigns(:static_content).should eq(static_content)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StaticContent" do
        expect {
          post :create, {:static_content => valid_attributes}, valid_session
        }.to change(StaticContent, :count).by(1)
      end

      it "assigns a newly created static_content as @static_content" do
        post :create, {:static_content => valid_attributes}, valid_session
        assigns(:static_content).should be_a(StaticContent)
        assigns(:static_content).should be_persisted
      end

      it "redirects to the created static_content" do
        post :create, {:static_content => valid_attributes}, valid_session
        response.should redirect_to(StaticContent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved static_content as @static_content" do
        # Trigger the behavior that occurs when invalid params are submitted
        StaticContent.any_instance.stub(:save).and_return(false)
        post :create, {:static_content => { "name" => "invalid value" }}, valid_session
        assigns(:static_content).should be_a_new(StaticContent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StaticContent.any_instance.stub(:save).and_return(false)
        post :create, {:static_content => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested static_content" do
        static_content = StaticContent.create! valid_attributes
        # Assuming there are no other static_contents in the database, this
        # specifies that the StaticContent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StaticContent.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => static_content.to_param, :static_content => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested static_content as @static_content" do
        static_content = StaticContent.create! valid_attributes
        put :update, {:id => static_content.to_param, :static_content => valid_attributes}, valid_session
        assigns(:static_content).should eq(static_content)
      end

      it "redirects to the static_content" do
        static_content = StaticContent.create! valid_attributes
        put :update, {:id => static_content.to_param, :static_content => valid_attributes}, valid_session
        response.should redirect_to(static_content)
      end
    end

    describe "with invalid params" do
      it "assigns the static_content as @static_content" do
        static_content = StaticContent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StaticContent.any_instance.stub(:save).and_return(false)
        put :update, {:id => static_content.to_param, :static_content => { "name" => "invalid value" }}, valid_session
        assigns(:static_content).should eq(static_content)
      end

      it "re-renders the 'edit' template" do
        static_content = StaticContent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StaticContent.any_instance.stub(:save).and_return(false)
        put :update, {:id => static_content.to_param, :static_content => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested static_content" do
      static_content = StaticContent.create! valid_attributes
      expect {
        delete :destroy, {:id => static_content.to_param}, valid_session
      }.to change(StaticContent, :count).by(-1)
    end

    it "redirects to the static_contents list" do
      static_content = StaticContent.create! valid_attributes
      delete :destroy, {:id => static_content.to_param}, valid_session
      response.should redirect_to(static_contents_url)
    end
  end

end
