require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UsersPhotosController do

  # This should return the minimal set of attributes required to create a valid
  # UsersPhoto. As you add validations to UsersPhoto, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "user_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UsersPhotosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all users_photos as @users_photos" do
      users_photo = UsersPhoto.create! valid_attributes
      get :index, {}, valid_session
      assigns(:users_photos).should eq([users_photo])
    end
  end

  describe "GET show" do
    it "assigns the requested users_photo as @users_photo" do
      users_photo = UsersPhoto.create! valid_attributes
      get :show, {:id => users_photo.to_param}, valid_session
      assigns(:users_photo).should eq(users_photo)
    end
  end

  describe "GET new" do
    it "assigns a new users_photo as @users_photo" do
      get :new, {}, valid_session
      assigns(:users_photo).should be_a_new(UsersPhoto)
    end
  end

  describe "GET edit" do
    it "assigns the requested users_photo as @users_photo" do
      users_photo = UsersPhoto.create! valid_attributes
      get :edit, {:id => users_photo.to_param}, valid_session
      assigns(:users_photo).should eq(users_photo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UsersPhoto" do
        expect {
          post :create, {:users_photo => valid_attributes}, valid_session
        }.to change(UsersPhoto, :count).by(1)
      end

      it "assigns a newly created users_photo as @users_photo" do
        post :create, {:users_photo => valid_attributes}, valid_session
        assigns(:users_photo).should be_a(UsersPhoto)
        assigns(:users_photo).should be_persisted
      end

      it "redirects to the created users_photo" do
        post :create, {:users_photo => valid_attributes}, valid_session
        response.should redirect_to(UsersPhoto.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved users_photo as @users_photo" do
        # Trigger the behavior that occurs when invalid params are submitted
        UsersPhoto.any_instance.stub(:save).and_return(false)
        post :create, {:users_photo => { "user_id" => "invalid value" }}, valid_session
        assigns(:users_photo).should be_a_new(UsersPhoto)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UsersPhoto.any_instance.stub(:save).and_return(false)
        post :create, {:users_photo => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested users_photo" do
        users_photo = UsersPhoto.create! valid_attributes
        # Assuming there are no other users_photos in the database, this
        # specifies that the UsersPhoto created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        UsersPhoto.any_instance.should_receive(:update_attributes).with({ "user_id" => "1" })
        put :update, {:id => users_photo.to_param, :users_photo => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested users_photo as @users_photo" do
        users_photo = UsersPhoto.create! valid_attributes
        put :update, {:id => users_photo.to_param, :users_photo => valid_attributes}, valid_session
        assigns(:users_photo).should eq(users_photo)
      end

      it "redirects to the users_photo" do
        users_photo = UsersPhoto.create! valid_attributes
        put :update, {:id => users_photo.to_param, :users_photo => valid_attributes}, valid_session
        response.should redirect_to(users_photo)
      end
    end

    describe "with invalid params" do
      it "assigns the users_photo as @users_photo" do
        users_photo = UsersPhoto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UsersPhoto.any_instance.stub(:save).and_return(false)
        put :update, {:id => users_photo.to_param, :users_photo => { "user_id" => "invalid value" }}, valid_session
        assigns(:users_photo).should eq(users_photo)
      end

      it "re-renders the 'edit' template" do
        users_photo = UsersPhoto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UsersPhoto.any_instance.stub(:save).and_return(false)
        put :update, {:id => users_photo.to_param, :users_photo => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested users_photo" do
      users_photo = UsersPhoto.create! valid_attributes
      expect {
        delete :destroy, {:id => users_photo.to_param}, valid_session
      }.to change(UsersPhoto, :count).by(-1)
    end

    it "redirects to the users_photos list" do
      users_photo = UsersPhoto.create! valid_attributes
      delete :destroy, {:id => users_photo.to_param}, valid_session
      response.should redirect_to(users_photos_url)
    end
  end

end
